function actions = suggestNextActions(scope, plan)
%SUGGESTNEXTACTIONS Return compact, deterministic, cost-aware next calls.
if nargin < 2 || isempty(plan)
    plan = struct('allowBroadDeep', false);
end
actions = struct('tool',{},'args',{},'reason',{},'cost',{});
scope = char(scope);

actions(end+1) = struct('tool','model_query_params', ...
    'args',struct('targets',['["' scope '"]'],'params','["all"]','compile','false'), ...
    'reason',['Query selected parameters for ' scope ' when parameter values are needed.'], ...
    'cost','cheap-live-targeted');

actions(end+1) = struct('tool','model_read', ...
    'args',struct('scope',scope,'depth','0'), ...
    'reason','Use a fresh shallow read of the exact target scope when current block IDs, ports, or algorithmic expressions are needed before editing/debugging.', ...
    'cost','targeted-shallow');

actions(end+1) = struct('tool','model_check', ...
    'args',struct('scope',scope,'checks','["all"]'), ...
    'reason','Run scoped structural checks after edits or when validating suspected issues.', ...
    'cost','medium');

if isfield(plan,'allowBroadDeep') && plan.allowBroadDeep
    actions(end+1) = struct('tool','model_read', ...
        'args',struct('scope',scope,'depth','1'), ...
        'reason','A broader read was explicitly allowed; still prefer one scoped level before any full recursive read.', ...
        'cost','expensive');
end
end
